# Generated by Django 6.0 on 2026-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Administrator')], default='normal', max_length=10),
        ),
    ]
