# Generated by Django 6.0.1 on 2026-01-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics (Phones, Laptops)'), ('documents', 'Documents (ID, Passport, Wallet)'), ('pets', 'Pets & Animals'), ('accessories', 'Accessories (Keys, Glasses, Bags)'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
