# Generated by Django 6.0.1 on 2026-01-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='proof_description',
            field=models.TextField(help_text='Describe details only the owner would know.'),
        ),
    ]
