# Generated by Django 6.0 on 2026-01-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_claim_verification_date_claim_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('ownership', 'Ownership Claim'), ('found_my_item', 'Found My Lost Item')], default='ownership', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the verification', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=15),
        ),
    ]
